/* tslint:disable */
/* eslint-disable */
/*
 * Globalize Culture it-IT
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function (window, undefined) {

	var Globalize;

	if (typeof require !== "undefined" &&
		typeof exports !== "undefined" &&
		typeof module !== "undefined") {
		// Assume CommonJS
		Globalize = require("globalize");
	} else {
		// Global variable
		Globalize = window.Globalize;
	}

	Globalize.addCultureInfo("es-CL", "default", {
		name: "es-CL",
		englishName: "Spanish (Italy)",
		nativeName: "Espanol (Italia)",
		language: "es",
		numberFormat: {
			".": ",",
			",": ".",
			"NaN": "Non un numero reale",
			negativeInfinity: "-Infinito",
			positiveInfinity: "+Infinito",
			percent: {
				pattern: ["-n%", "n%"],
				".": ",",
				",": ".",
			},
			currency: {
				pattern: ["-$ n", "$ n"],
				".": ",",
				",": ".",
				symbol: "€"
			}
		},
		calendars: {
			standard: {
				firstDay: 1,
				days: {
					names: ["Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"],
					// abbreviated day names
					namesAbbr: ["Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
					// shortest day names
					namesShort: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"]
				},
				months: {
					// full month names (13 months for lunar calendards -- 13th month should be "" if not lunar)
					names: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", ""],
					// abbreviated month names
					namesAbbr: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic", ""]
				},
				AM: null,
				PM: null,
				eras: [{ "name": "d.C.", "start": null, "offset": 0 }],
				patterns: {
					d: "dd/MM/yyyy",
					D: "dddd d MMMM yyyy",
					t: "HH:mm",
					T: "HH:mm:ss",
					f: "dddd d MMMM yyyy HH:mm",
					F: "dddd d MMMM yyyy HH:mm:ss",
					M: "dd MMMM",
					Y: "MMMM yyyy"
				}
			}
		}
	});

}(this));