 SELECT CODTERM,CODPROD,NOMTERM,CODSTOCKB,foprte.*  FROM foprte
 WHERE CODSTOCKB =10108317 ;
 
  SELECT CODTERM,CODPROD,NOMTERM,CODSTOCKB,foprte.*  FROM foprte
 WHERE CODSTOCKB =40047; -- MATERIA PRIMA
 
  SELECT CODTERM,CODPROD,NOMTERM,CODSTOCKB,foprte.*  FROM foprte
 WHERE CODPROD  LIKE '%808024%'
 
   SELECT CODTERM,CODPROD,NOMTERM,CODSTOCKB,foprte.*  FROM foprte
 WHERE CODPROD  LIKE '%125053%'
 