select MONUMERO, MOVIMIENTO.* from MOVIMIENTO where  TO_CHAR(N_MOFECHA, 'YYYY-MM-DD') >='2024-10-22' and MONUMERO =1000581  ORDER BY 1


select * from VENTA_TRG_LOG

select * from VENTAS where  TO_CHAR(N_VEFECEMI, 'YYYY-MM-DD') >'2024-10-10' and VENRODOC = 1000581 ORDER BY VENRODOC

select * from VENTAS where  TO_CHAR(N_VEFECEMI, 'YYYY-MM-DD') >='2024-10-22' AND  VENRODOC NOT IN (
select MONUMERO from MOVIMIENTO where  TO_CHAR(N_MOFECHA, 'YYYY-MM-DD') >='2024-10-10' ) 
 