create table VENTA_TRG_LOG
( VENRODOC NUMBER (10),
  FECHACREACION DATE DEFAULT SYSDATE )
  
  CREATE  TRIGGER TRG_VENTAS_LOG
AFTER INSERT OR DELETE ON VENTAS
FOR EACH ROW
BEGIN
    -- Si es una inserción, agregar un registro a VENTA_TRG_LOG
    IF INSERTING THEN
        INSERT INTO VENTA_TRG_LOG (VENRODOC, FECHACREACION)
        VALUES (:NEW.VENRODOC, SYSDATE);
    END IF;

    -- Si es una eliminación, eliminar el registro correspondiente en VENTA_TRG_LOG
    IF DELETING THEN
        DELETE FROM VENTA_TRG_LOG WHERE VENRODOC = :OLD.VENRODOC;
    END IF;
END TRG_VENTAS_LOG;