 
 --SELECT * FROM VENTAS WHERE VENRODOC =936617
;
 VEMONTO NETO + IVA Y POSITIVO LOS 2 VALORES.
 
SELECT * FROM  API_BOLETA WHERE BONUMERO =-936617
 ;
SELECT *  FROM API_VENTAS WHERE VENRODOC= 936617

;
SELECT * FROM API_MOVIMIENTO WHERE MONUMERO= -936617

;
  --SELECT *  FROM  MOVIMIENTO WHERE MONUMERO= -936617;