select * from MOVIMIENTO where  TO_CHAR(N_MOFECHA, 'YYYY-MM-DD') ='2024-10-22' ORDER BY MONUMERO


select * from VENTAS where  TO_CHAR(N_VEFECEMI, 'YYYY-MM-DD')='2024-10-22' ORDER BY VENRODOC


select * from VENTAS where  TO_CHAR(N_VEFECEMI, 'YYYY-MM-DD') ='2024-10-22' AND  VENRODOC NOT IN (
select MONUMERO from MOVIMIENTO where  TO_CHAR(N_MOFECHA, 'YYYY-MM-DD') ='2024-10-22' ) 
 