 
--   CREATE SEQUENCE  "CMANBAS"."SEQ_T_LOGAPP"  MINVALUE 1 MAXVALUE 99999999999999999 INCREMENT BY 1 START WITH 1  NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  CREATE TABLE "CMANBAS"."T_LOG_APP" 
   (	"LOGCORR" NUMBER(10,0) DEFAULT  "CMANBAS"."SEQ_T_LOGAPP".NEXTVAL   NOT NULL ENABLE, 
	"LOGAPP" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LOGMENU" VARCHAR2(50 BYTE)   NOT NULL ENABLE, 
   "LOGFECHA" TIMESTAMP  DEFAULT SYSDATE NOT NULL ENABLE,
	"LOGEVENTO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LOGLOGIN" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LOGDESC" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "T_LOG_APP_PK" PRIMARY KEY ("LOGCORR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )