SELECT T_PLANREMUNERACION.VERSION, 
GERENCIA,
T_GRUPO.ORDENGRUPO, 
T_GRUPOITEM.CODGRUPO,
T_GRUPO.DESGRUPO,
T_PLANREMUNERACION.CODINTERNOGERENCIA,
T_PLANREMUNERACION.CODITEM,DESITEM,
ENERO,FEBRERO,MARZO,ABRIL,MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE 
FROM T_PLANREMUNERACION , T_GERENCIA , T_GRUPOITEM,T_GRUPO
WHERE T_PLANREMUNERACION.CODINTERNOGERENCIA = T_GERENCIA.CODINTERNO
   AND T_PLANREMUNERACION.CODITEM = T_GRUPOITEM.CODITEM
   AND T_GRUPO.CODGRUPO = T_GRUPOITEM.CODGRUPO 
   ORDER BY  T_PLANREMUNERACION.VERSION, 
GERENCIA, T_PLANREMUNERACION.CODITEM,
T_GRUPO.ORDENGRUPO;