SELECT VENTAS.VENRODOC ,
VENTAS.VENROPED,VENTAS.VERUT,N_VEFECEMI, substr(CODPROD, 1, 6) PRODBAGO , MOPRECLIS, MOPRECREAL, ROUND(MOCANDES) ,PRECIOLISTA.* ,

(VALOR - ROUND(MOCANDES)   ) DIFERENCIA 


 
  FROM VENTAS, MOVIMIENTO, CLIENTES , (
 SELECT substr(codterm, 1, 6) codtermPL, nomterm, pl_valor valor, pl_tipo 
                      FROM tablas.foprte, precios_licitacion
                      WHERE substr(pl_codigo, 1, 6) = substr(codterm, 1, 6) 
                      AND  to_char(pl_fechaini, 'yyyymm') >= '202306' )  PRECIOLISTA
WHERE MOVIMIENTO.MONUMERO = VENTAS.VENRODOC AND VENTAS.VECODCLI = CLIENTES.CLCODIGO
AND substr(CODPROD, 1, 6) = codtermPL  AND  TO_CHAR(N_VEFECEMI, 'YYYY-MM-DD')>='2023-08-23'  AND VETIPDOC='FA'
 AND  SUBSTR(CODINTELI, 4, 1)=2
 
 ORDER BY  N_VEFECEMI
 
 
SELECT 
VENTAS.VENROPED,VENTAS.VERUT,N_VEFECEMI, substr(CODPROD, 1, 6) PRODBAGO ,    MOVIMIENTO.*
 
  FROM VENTAS, MOVIMIENTO, CLIENTES 
WHERE MOVIMIENTO.MONUMERO = VENTAS.VENRODOC AND VENTAS.VECODCLI = CLIENTES.CLCODIGO AND
  TO_CHAR(N_VEFECEMI, 'YYYY-MM-DD')>='2023-08-22'  AND VETIPDOC='FA'
 