
  CREATE TABLE "REMUNE"."T_CARGOSCECO" 
   (	 CODIGOINTERNOCARGO  NUMBER(10,0) NOT NULL primary key, 
       DESCCARGO VARCHAR2(150) NOT NULL,
    	"CODINTERNOGERENCIA" NUMBER(10,0) NULL
   ) 
   CREATE SEQUENCE  "REMUNE"."SEQ_CARGOSCECO"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;