--------------------------------------------------------
--  Constraints for Table T_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "REMUNE"."T_EMPLEADO" ADD CONSTRAINT "PK_T_EMPLEADO_RUT" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REMUNETS"  ENABLE;
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("RUT" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("APELLIDOPATERNO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("APELLIDOMATERNO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("SEXO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("CARGO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("CENTROCOSTO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("DESCENTROCOSTO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("FECHAINGRESO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("GERENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADO" MODIFY ("CENTROCOSTOPADRE" NOT NULL ENABLE);
