--------------------------------------------------------
--  Constraints for Table T_EMPLEADORENTA
--------------------------------------------------------

  ALTER TABLE "REMUNE"."T_EMPLEADORENTA" ADD CONSTRAINT "PK_T_EMPLEADORENTA_RUTPERVERS" PRIMARY KEY ("RUT", "PERIODO", "VERSIONDATA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REMUNETS"  ENABLE;
 
  ALTER TABLE "REMUNE"."T_EMPLEADORENTA" MODIFY ("RUT" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADORENTA" MODIFY ("VERSIONDATA" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADORENTA" MODIFY ("PERIODO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADORENTA" MODIFY ("AGNO" NOT NULL ENABLE);
 
  ALTER TABLE "REMUNE"."T_EMPLEADORENTA" MODIFY ("MES" NOT NULL ENABLE);
