--------------------------------------------------------
--  DDL for Table T_EMPLEADORENTA
--------------------------------------------------------

  CREATE TABLE "REMUNE"."T_EMPLEADORENTA" 
   (	"RUT" VARCHAR2(12 BYTE), 
	"VERSIONDATA" NUMBER(10,0), 
	"PERIODO" VARCHAR2(7 BYTE), 
	"AGNO" NUMBER(4,0), 
	"MES" NUMBER(2,0), 
	"RENTABRUTA" NUMBER(10,2), 
	"RENTABRUTANEW" NUMBER(10,2), 
	"CECO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REMUNETS" ;
