--------------------------------------------------------
--  DDL for Table T_EMPLEADO
--------------------------------------------------------

  CREATE TABLE "REMUNE"."T_EMPLEADO" 
   (	"RUT" VARCHAR2(15 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDOPATERNO" VARCHAR2(50 BYTE), 
	"APELLIDOMATERNO" VARCHAR2(50 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"CARGO" VARCHAR2(100 BYTE), 
	"CENTROCOSTO" VARCHAR2(10 BYTE), 
	"DESCENTROCOSTO" VARCHAR2(100 BYTE), 
	"FECHAINGRESO" DATE, 
	"CODINTERNOGERENCIA" NUMBER(10,0), 
	"GERENCIA" VARCHAR2(150 BYTE), 
	"SINDICATO" VARCHAR2(150 BYTE), 
	"IND_BONO_ASIS_YPRODUCC" NUMBER(3,0), 
	"TIPOCONVENIO" VARCHAR2(20 BYTE), 
	"TIPOMOVILIZACION" VARCHAR2(50 BYTE), 
	"CENTROCOSTOPADRE" VARCHAR2(10 BYTE), 
	"COMENTARIOS" VARCHAR2(150 BYTE), 
	"VERSIONDATA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REMUNETS" ;
