--------------------------------------------------------
--  DDL for Table T_GERENCIA
--------------------------------------------------------

  CREATE TABLE "REMUNE"."T_GERENCIA" 
   (	"CODINTERNO" NUMBER(10,0), 
	"GERENCIA" VARCHAR2(100 BYTE), 
	"CODEMPRESA" VARCHAR2(10 BYTE), 
	"RUT" VARCHAR2(12 BYTE), 
	"CLAVE" VARCHAR2(30 BYTE), 
	"MONTOAUMENTO" NUMBER(12,2), 
	"ADMINISTRADOR" VARCHAR2(1 BYTE), 
	"CLAVEENC" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"GERCENTROCOSTO" VARCHAR2(30 BYTE), 
	"MONTONEGOCIACIONC" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "REMUNETS" ;
