INSERT INTO T_VENTAS_PRODUCCION (agnomes,  codigo, descripcion, valor, CAMPO1, CAMPO2,agno, mes )
select * from (
WITH FECHAS AS (
  SELECT TO_CHAR(ADD_MONTHS(DATE '2022-01-01', LEVEL - 1), 'YYYYMM') AS ANOMES,
         EXTRACT(YEAR FROM ADD_MONTHS(DATE '2022-01-01', LEVEL - 1)) AS AGNO,
         EXTRACT(MONTH FROM ADD_MONTHS(DATE '2022-01-01', LEVEL - 1)) AS MES
  FROM DUAL
  CONNECT BY LEVEL <= 12 * (EXTRACT(YEAR FROM SYSDATE) - 2023 + 3)
)
SELECT F.ANOMES, 
       NVL(T.CODIGO, T2.CODPROD) AS CODIGO, 
       NVL(T.DESCRIPCION, T2.NOMTERM) AS DESCRIPCION, 
       NVL(T.MOVIMIENTO, 0) + NVL(T2.CANTIDAD, 0) AS MOVIMIENTO,
       0 AS CAMPO1,
       0 AS CAMPO2,
       F.AGNO,
       F.MES
FROM FECHAS F
LEFT JOIN (
    SELECT A.CODPROD CODIGO, B.NOMTERM DESCRIPCION, 
           SUM(NVL(A.MOCANSAL, 0) - NVL(MOCANING, 0)) MOVIMIENTO,
           TO_CHAR(N_MOFECHA, 'YYYYMM') ANOMES
    FROM MOVIMIENTO A
    JOIN TABLAS.FOPRTE B ON A.CODPROD = B.CODTERM
    WHERE A.MOTIPDOC || SUBSTR(NVL(MOTIPBOL, '*'), 1, 1) IN ('FA*', 'BOD')
    GROUP BY A.CODPROD, B.NOMTERM, TO_CHAR(N_MOFECHA, 'YYYYMM')
) T ON F.ANOMES = T.ANOMES
LEFT JOIN (
    SELECT DET_EXP.CODPROD, FOPRTE.NOMTERM, 
           SUM(DET_EXP.CANTIDAD) CANTIDAD, 
           TO_CHAR(FECHA, 'YYYYMM') ANOMES
    FROM FACTURAS.DET_EXP DET_EXP
    JOIN FACTURAS.ENC_EXP ENC_EXP ON ENC_EXP.NROP = DET_EXP.NROP
    JOIN TABLAS.FOPRTE FOPRTE ON DET_EXP.CODPROD = FOPRTE.CODTERM
    GROUP BY DET_EXP.CODPROD, FOPRTE.NOMTERM, TO_CHAR(FECHA, 'YYYYMM')
) T2 ON F.ANOMES = T2.ANOMES AND T.CODIGO = T2.CODPROD
ORDER BY F.ANOMES, CODIGO ) xxx;